name: Eastwood

on: [push, pull_request]

jobs:

  eastwood:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - name: Run Eastwood
      run: |
        set -o pipefail
        lein with-profile +ci,+oss eastwood | tee eastwood.log
    - name: Convert linter output to annotations
      run: ./bin/convert2annotations.js eastwood.log eastwood-annotations.json
      if: always()
    - name: Upload linter annotations
      uses: yuzutech/annotations-action@v0.1.0
      if: always()
      with:
        input: './eastwood-annotations.json'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
